### ISSUE TITLE
Is this lib for https://helpcrunch.com/ 

### ISSUE THREAD

**Issue by Sharqiyem** [KyteApp/react-native-helpcrunch#1]
Could you tell me please what is RNHelpCrunch from documentation ?

Thanks in advanced.

**Comment by ital0** [comment]
Hey @Sharqiyem 
Yes, this lib is for HelpCrunch.
I'm sorry, I didn't have time to write any documentation. If so, you could read the code and try to understand and then you could post here if you got any doubts.
